# Default values for thor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global configuration
global:
  # -- (bool) Whether the deployment is for development purposes.
  dev: true
  # -- (string) Environment name. This should be the same as vpcname if you're doing an AWS deployment. Currently this is being used to share ALB's if you have multiple namespaces. Might be used other places too.
  environment: default
  # -- (int) The minimum amount of pods that are available at all times if the PDB is deployed.
  minAvailable: 1

# -- (bool) Whether Metrics are enabled.
metricsEnabled:

# Deployment
# -- (int) Number of replicas for the deployment.
replicaCount: 1

# -- (map) Docker image information.
image:
  # -- (string) Docker repository.
  repository: quay.io/cdis/thor
  # -- (string) Docker pull policy.
  pullPolicy: Always
  # -- (string) Overrides the image tag whose default is the chart appVersion.
  tag: "master"

# Service and Pod
# -- (map) Kubernetes service information.
service:
  # -- (int) The port number that the service exposes.
  port: 80
  targetPort: 8000

# -- (list) Environment variables to pass to the container
env:
  - name: AWS_DEFAULT_REGION
    value: us-east-1
  - name: GITHUB_TOKEN
    valueFrom:
      secretKeyRef:
        name: thor-g3auto
        key: "github_token"
  - name: SLACK_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: thor-g3auto
        key: "slacktoken"
  - name: SLACK_WEBHOOK
    valueFrom:
      secretKeyRef:
        name: thor-g3auto
        key: "slack_webhook"
  - name: JIRA_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: thor-g3auto
        key: "jira_api_token"

# -- (list) Volumes to mount to the container.
volumeMounts:
  - name: thor-g3auto
    mountPath: "/src/thor.env"
    subPath: thor.env
    readOnly: true

# -- (list) Volumes to attach to the container.
volumes:
  - name: thor-g3auto
    secret:
      secretName: thor-g3auto #pragma: allowlist secret

# -- (map) Resource requests and limits for the containers in the pod
resources:
  requests:
    cpu: 1
  limits:
    cpu: 2
    memory: 512Mi

secretStoreServiceAccount:
  # -- (bool) Set true if deploying to AWS and want to use service account and IAM role.
  enabled: true
  # -- (string) Name of the service account to create
  name: secret-store-sa
  # -- (string) AWS Role ARN for Secret Store to use
  roleArn: arn:aws:iam::707767160287:role/devplanetv2-external-secrets-sa
externalSecrets:
  secretName: devplanetv2-thor-g3auto #pragma: allowlist secret

# -- (map) Configuration for ingress.
ingress:
  scheme: internal
  environment: "devplanetv2"
  certArn: "arn:aws:acm:us-east-1:707767160287:certificate/f427a646-94fd-4b91-8bcd-80f5920c1e46"
  group: "devplanetv2-internal"
  sslPolicy: "ELBSecurityPolicy-TLS13-1-2-Res-FIPS-2023-04"
  host: thor.ci.planx-pla.net
