kind: Service
apiVersion: v1
metadata:
  name: thor
spec:
  selector:
    app: thor
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: http