name: CI

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    services:
        postgres:
          image: postgres
          env:
            POSTGRES_PASSWORD: postgres #pragma: allowlist secret
          ports:
            - 5432:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5   
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install -vv
    - name: List installed packages
      run: pip list
    - name: Create test database
      run: |
        psql -h localhost -p 5432 -U postgres -c "CREATE DATABASE thor_test_tmp;"
      env:
        PGPASSWORD: postgres #pragma: allowlist secret
    - name: Run migrations
      env:
          DEVELOPMENT: true
      run: poetry run python src/thor/create_all_tables.py
    - name: Run tests
      env:
        DEVELOPMENT: true
      run: |
        poetry run pytest --cov=src --cov-fail-under=60 --cov-report xml -vv -s tests

  image_build_push:
    name: Build Image and Push
    # TODO Uncomment after PXP-9212
    # needs: Security
    uses: uc-cdis/.github/.github/workflows/image_build_push.yaml@master
    with:
      USE_QUAY_ONLY: true
    secrets:
      ECR_AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
      ECR_AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
