name: CI

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:

  build:

    runs-on: ubuntu-latest

    services:
        postgres:
          image: postgres
          env:
            POSTGRES_PASSWORD: postgres #pragma: allowlist secret
          ports:
            - 5432:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install -vv
    - name: Create test database
      run: |
        psql -U postgres -c "CREATE DATABASE thor_test_tmp;"
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        PGPASSWORD: postgres #pragma: allowlist secret
    - name: Run migrations
      env:
        DEVELOPMENT: true  
      run: poetry run python src/thor/create_all_tables.py
    - name: List installed packages
      run: pip list
    - name: Run tests
      env:
        DEVELOPMENT: true
      run: |
        poetry run pytest --cov=src --cov-fail-under=60 --cov-report xml -vv -s tests