name: CI

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install -vv
    - name: Set up Postgres
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '9.6' 
        postgresql db: test_db
    - name: Create test database
      run: |
        psql -U postgres -c "CREATE DATABASE thor_test_tmp;"
    - name: Run migrations
      env:
        DEVELOPMENT: true  
      run: poetry run python src/thor/create_all_tables.py
    - name: List installed packages
      run: pip list
    - name: Run tests
      env:
        DEVELOPMENT: true
      run: |
        poetry run pytest --cov=src --cov-fail-under=60 --cov-report xml -vv -s tests