name: Build docs

on:
  push

jobs:
  build_docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/cache@preview
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles(format('{0}{1}', github.workspace, '/poetry.lock')) }}
        restore-keys: |
          ${{ runner.os }}-poetry-
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install poetry
        poetry install
    - name: Build docs
      run: poetry run python docs.py openapi

    - uses: stefanzweifel/git-auto-commit-action@v4.1.2
      with:
        commit_message: Apply automatic documentation changes

        # Optional name of the branch the commit should be pushed to
        # Required if Action is used in Workflow listening to the `pull_request` event
        branch: ${{ github.head_ref }}
