name: Tests

on: pull_request

jobs:
  runTests:
    name: Run unit Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:9.6-bullseye
        env:
          POSTGRES_DB: thor_test_tmp
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
        ports:
          - 5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-versions: 3.9
    
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install poetry
        poetry install -vv

    - name: Init postgres db
      run: |
        psql -c 'SELECT version();' -U postgres
        psql -U postgres -c "create database thor_test_tmp"
        DEVELOPMENT=true poetry run python src/thor/create_all_tables.py

    - name: pip list
      run: pip list

    - name: Run Tests
      run: DEVELOPMENT=true poetry run pytest --cov=src --cov-fail-under=60 --cov-report xml -vv -s tests
